version: "3.6"

# https://github.com/mattermost/mattermost-docker/blob/5.7.1/contrib/swarm/docker-stack-traefik.yml

services:

  db:
      # use official mattermost prod-db image
      image: mattermost/mattermost-prod-db
      networks:
        - mm-in
      volumes:
        # use a named-volume for data persistency
        # - mm-dbdata:/var/lib/postgresql/data
        # - /etc/localtime:/etc/localtime:ro
        - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
        # - /etc/localtime:/etc/localtime:ro
      environment:
        - POSTGRES_USER=mmuser
        - POSTGRES_PASSWORD=mmuser_password
        - POSTGRES_DB=mattermost
        # uncomment the following to enable backup
        # - AWS_ACCESS_KEY_ID=XXXX
        # - AWS_SECRET_ACCESS_KEY=XXXX
        # - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
        # - AWS_REGION=us-east-1
      labels:
        - traefik.enable=false

  mattermost:
    # use official mattermost prod-app image
    image: mattermost/mattermost-prod-app
    networks:
      - mm-in
      - web
    # ports:
    #   - 20080:8000
    volumes:
      # - /var/lib/mattermost/config:/mattermost/config:rw
      # - /var/lib/mattermost/data:/mattermost/data:rw
      # - /var/lib/mattermost/logs:/mattermost/logs:rw
      # - /var/lib/mattermost/plugins:/mattermost/plugins:rw
      # - /etc/localtime:/etc/localtime:ro
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      # - /etc/localtime:/etc/localtime:ro
    environment:
      # use service's hostname
      - DB_HOST=db
      # talk to the port within the overlay network
      # without (over)exposing ports
      - DB_PORT_NUMBER=5432
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      # pass the edition to be used, default is enterprise
      # setting this env var will make the app use the team edition
      - edition=team
      # in case your config is not in default location
      # - MM_CONFIG=/mattermost/config/config.json
    labels:
      - "traefik.backend.loadbalancer.sticky=true"
      # - "traefik.backend.loadbalancer.swarm=true"
      # the backend service needs a name
      - "traefik.backend=mattermost"
      # network is prefixed `mm_` as well
      # - "traefik.docker.network=mm_mm-out"
      - "traefik.docker.network=web"
      # generate a TLS cert for this domain
      - "traefik.entrypoints=http"
      # - "traefik.frontend.passHostHeader=true"
      # add your domain below here
      # - "traefik.frontend.rule=Host:mattermost.domain.com"
      - "traefik.frontend.rule=Host:mattermost.home"
      - "traefik.port=8000"
    depends_on:
      - db

networks:
  web:
    external: true
    name: web
  mm-in:
    external: false