# rules.toml
[frontends]
    [frontends.traefik]
        backend = "traefik"
        passHostHeader = true
        entrypoints = ["https"]
        [frontends.traefik.routes]
            [frontends.traefik.routes.route]
            rule = "Host:traefik.home.m3"

[backends]
    [backends.traefik]
        [backends.traefik.LoadBalancer]
            method = "drr"
            [backends.traefik.loadbalancer.stickiness]
        [backends.traefik.servers] 
            [backends.traefik.servers.server1]
            url = "http://127.0.0.1:28080"
            weight = 1
##