#
version: '3.6'

services:
  m3:
      build:
        context: ./
        dockerfile: Dockerfile
      image: asperitus/m3:latest
      restart: always
      container_name: m3
      ports:
        - "80:80"
        - "443:443"
        - "1080:1080"
        - "8080:8080"
        - "10080:10080"
        - "18080:18080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./etc:/dhnt/etc
      entrypoint:
        - '/dhnt/bin/m3'
        - 'run'
        - '--base'
        - '/dhnt'
      labels:
        - traefik.enable=false

networks:
  default:
    external: true
    name: web
#
# docker network create web
#