#
version: '3.6'

services:
  m3os:
    build:
      context: ./
      dockerfile: Dockerfile
    image: asperitus/m3:latest
    restart: always
    container_name: m3os
    hostname: m3os
    ports:
      - "80:80"
      - "443:443"
      - "1080:1080"
      - "8080:8080"
      # - "8443:8443"
      - "18080:18080"
      # - "28080:28080"
      # - "38080:38080"
      # - "7000:7000"
      # etcd
      # - "2379:2379"
      # - "2380:2380"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - dhnt:/home/dhnt
      - ./dhnt/etc:/dhnt/etc
    entrypoint:
      - '/dhnt/bin/m3'
      - 'run'
      - '--base'
      - '/dhnt'
    labels:
      - traefik.enable=false
    networks:
      web:

  dui:
    image: asperitus/docker-compose-ui:latest
    restart: always
    container_name: dui
    hostname: dui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dhnt:/home/dhnt
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.backend.loadbalancer.stickiness=true"
      - "traefik.backend=dui"
      - "traefik.docker.network=web"
      - "traefik.entrypoints=http"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.rule=Host:dui.home"
      - "traefik.port=5000"

volumes:
  dhnt:

networks:
  web:
    external: false
    name: web
##