#
version: '3.6'

services:
  m3:
      build:
        context: ./
        dockerfile: Dockerfile
      image: asperitus/m3:latest
      restart: always
      container_name: m3
      hostname: m3os
      ports:
        - "80:80"
        - "443:443"
        - "1080:1080"
        - "8080:8080"
        - "8443:8443"
        - "18080:18080"
        # - "28080:28080"
        # - "38080:38080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./dhnt/etc:/dhnt/etc
        # - ./dhnt/home:/dhnt/home
        # - ./dhnt/data:/dhnt/data
      entrypoint:
        - '/dhnt/bin/m3'
        - 'run'
        - '--base'
        - '/dhnt'
      labels:
        - traefik.enable=false

networks:
  default:
    external: false
    name: web
#
# docker network create web
#