# https://github.com/bubuntux/docker-riot-web
# https://github.com/vector-im/riot-web#configjson
version: '3.6'

services:
  web:
    image: asperitus/riot-web
    container_name: riot
    restart: unless-stopped
    # networks:
    #   - web
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:riot.matrix.home"
      - "traefik.port=80"
      # - "traefik.docker.network=web"
    volumes:
      - ./config.json:/etc/riot-web/config.json:ro
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro 

networks:
  default:
    external:
      name: web