# rules.toml
[frontends]
    [frontends.term-myid]
        backend = "term-myid"
        passHostHeader = true
        entrypoints = ["https"]
        [frontends.term-myid.routes]
            [frontends.term-myid.routes.route]
            rule = "Host:term.921sm3fxr9v5wwh08d7nvnks5a37px0tdj8qd8e0cc60acy514r61r.m3"

[backends]
    [backends.term-myid]
        [backends.term-myid.LoadBalancer]
            method = "drr"
            [backends.term-myid.loadbalancer.stickiness]
        [backends.term-myid.servers] 
            [backends.term-myid.servers.server]
            url = "http://127.0.0.1:10022"
            weight = 1
##