API:
  Port: 58080
  AggregatorPort: 58081
  Username: username
  Password: password
  ForceHttps: false
Proxy:
  Port: 28080
  HealthcheckTimeoutMillis: 5000
  Backends:
  - Host: localhost
    Port: 58082
    StatusPort: 58082
    StatusEndpoint: /
    Name: backend-0
  - Host: localhost
    Port: 58083
    StatusPort: 58083
    StatusEndpoint: /
    Name: backend-1
HealthPort: 59200
StaticDir: static
