defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.dashboard]
    address = ":28081"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["admin:$apr1$vmrjiFcz$S.liCeIvXD6TJzsxlbU6e0"]
  [entryPoints.http]
    address = ":28080"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":28443"
      [entryPoints.https.tls]

[api]
  entrypoint="dashboard"

# [acme]
# email = "your_email@your_domain"
# storage = "acme.json"
# entryPoint = "https"
# onHostRule = true
#   [acme.httpChallenge]
#   entryPoint = "http"

[docker]
  domain = "home"
  watch = true
  network = "web"

# htpasswd -nb admin password 
# docker network create web
