version: '3.6'

services:
  wordpress:
    image: wordpress
    restart: always
    # ports:
    #   - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: demodb
    labels:
      - traefik.backend=wordpress
      - traefik.frontend.rule=Host:wordpress.home
      - traefik.docker.network=web
      - traefik.port=80
    networks:
      - internal
      - web
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: demodb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - internal
    labels:
      - traefik.enable=false

  dba:
    image: adminer:4.6.3-standalone
    # ports:
    #   - 8080:8080
    labels:
      - traefik.backend=dba
      - traefik.frontend.rule=Host:dba.wordpress.home
      - traefik.docker.network=web
      - traefik.port=8080
    networks:
      - internal
      - web
    depends_on:
      - db

networks:
  web:
    external: true
    name: web
  internal:
    external: false