##
logLevel = "DEBUG"

defaultEntryPoints = ["http"]

# https://docs.traefik.io/user-guide/kv-config/#upload-the-configuration-in-the-key-value-store

# 
[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
    # [entryPoints.dashboard.auth]
    #   [entryPoints.dashboard.auth.basic]
    #     users = ["admin:$apr1$vmrjiFcz$S.liCeIvXD6TJzsxlbU6e0"]
  [entryPoints.http]
    address = ":80"

[api]
  entrypoint="dashboard"

[docker]
  domain = "home"
  watch = true
  network = "web"

# htpasswd -nb admin password 
# docker network create web
