version: '3.6'

services:

  app:
    image: bigbluebutton/greenlight
    labels:
      - "traefik.backend=app"
      - "traefik.docker.network=web"
      - "traefik.default.protocol=http"
      # - "traefik.domain=bbb.home"
      # - "traefik.frontend.passHostHeader=true"
      # - traefik.frontend.rule=Host:fe.bbb.home,fe.bbb.921sm3fxr9v5wwh08d7nvnks5a37px0tdj8qd8e0cc60acy514r61r
      - "traefik.frontend.rule=Host:fe.bbb.home"
      - "traefik.port=80"
      - "traefik.enable=true"
    networks:
      - web
    hostname: fe.bbb.home
    entrypoint: [bin/start]
    container_name: bbb-greenlight
    # env_file: env
    environment:
      - SECRET_KEY_BASE=65f3db279dde4a41ead326fc60b0b2e4c5ce9579073c3c79353188bddc29b958fd2d436c4709fc53795e781b48ed549021f19f66e93cbaea94e2d0f610dd864a
      - BIGBLUEBUTTON_ENDPOINT=http://bbb.home/bigbluebutton/
      - BIGBLUEBUTTON_SECRET=3ce47f0abd9beac3a66520c43e108820
      - ALLOW_GREENLIGHT_ACCOUNTS=true
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_DOMAIN=gmail.com
      - SMTP_AUTH=plain
      - SMTP_STARTTLS_AUTO=true
      - RELATIVE_URL_ROOT=/b
    restart: always
    # ports:
    #   - 5000:80
    volumes:
      - ./db/production:/usr/src/app/db/production
      - ./log:/usr/src/app/log
#    logging:
#      driver: $LOG_DRIVER
#      options:
#        syslog-address: $LOG_ADDRESS
#        tag: $LOG_TAG

networks:
  web:
    external:
      name: web